Add redis module
terraform-alicloud-modules/terraform-alicloud-redis pull request #3
Opened 2020-01-03 08:07 UTC by Rich-yi

2020-01-03 10:39 UTC, xiaozhu36 requested changes

2020-01-03 10:39 UTC, xiaozhu36 commented on .gitignore
> -*.tfstate.*
这个文件我觉得只有新增才对啊，没有要删除和修改的，为啥要删掉一些

2020-01-03 10:39 UTC, xiaozhu36 commented on README.md
> +
readme中不需要写inputs和outputs

2020-01-03 10:39 UTC, xiaozhu36 commented on examples/redis/README.md
> +
example的readme不需要这么复杂

2020-01-03 10:39 UTC, xiaozhu36 commented on examples/redis/main.tf
> +  ]
同样使用default的vpc

2020-01-03 10:39 UTC, xiaozhu36 commented on localse.tf
> +locals {
文件名称没改

2020-01-03 10:39 UTC, xiaozhu36 commented on localse.tf
> +  available_resource_creation = "KVStore"
把vswitch,vpc,和zone 的datasource都去掉把，包括vswitch的过滤条件，之间传递vswitchid就行

2020-01-03 10:39 UTC, xiaozhu36 commented on main.tf
> +  configuration_source    = "terraform-alicloud-modules/Redis"
redis，不是Redis

2020-01-03 10:39 UTC, xiaozhu36 commented on main.tf
> +  account_password = var.account_password
把account的所有参数都支持上，并且把account单独抽象为一个submodule

2020-01-03 10:39 UTC, xiaozhu36 commented on modules/redis/outputs.tf
> +output "this_kv_instance_id" {
把kv换成redis

2020-01-03 10:39 UTC, xiaozhu36 commented on variables.tf
> +variable "create_backup_policy" {
不用create_backup_policy，去掉

2020-01-03 10:39 UTC, xiaozhu36 commented on variables.tf
> +    For     = "acceptance test"
不用的code就去掉

2020-01-04 05:48 UTC, Rich-yi commented on examples/redis/main.tf
> +  ]
任务需求不是需要创建vpc吗？

2020-01-06 02:47 UTC, xiaozhu36 requested changes

2020-01-06 02:47 UTC, xiaozhu36 commented on examples/redis/main.tf
> +  output_file = "v.txt"
不要output file

2020-01-06 02:47 UTC, xiaozhu36 commented on examples/redis/main.tf
> +  name     ="redisxxx"
不要xxx，要定一个有意义的

2020-01-06 02:47 UTC, xiaozhu36 commented on examples/redis/v.txt
> +[
这个是要去掉的

2020-01-06 02:47 UTC, xiaozhu36 commented on main.tf
> +  instance_name        = substr("${var.instance_name}-${random_uuid.this.result}",0 ,256 )
这个不用random，就一个instance，没必要

2020-01-06 02:47 UTC, xiaozhu36 commented on main.tf
> +module "account" {
这个account要支持创建多个，类似rds的databases

2020-01-06 02:47 UTC, xiaozhu36 commented on variables.tf
> +variable "backup_time" {
我理解这个应该是一个list吧

2020-01-06 02:47 UTC, xiaozhu36 commented on modules/redis/README.md
> +# Redis-5.0 Alibaba Cloud Redis Terraform Module
这个module的name应该是redis-5.0 吧

2020-01-06 09:54 UTC, xiaozhu36 requested changes

2020-01-06 09:54 UTC, xiaozhu36 commented on README.md
> +---
这个Readme的title正确的改法是把第一行和第二行互换

2020-01-06 09:54 UTC, xiaozhu36 commented on examples/redis/README.md
> +terraform-alicloud-rds
example的readme不需要这么复杂

2020-01-06 09:54 UTC, xiaozhu36 commented on examples/redis/main.tf
> +
多余的空行可以删掉了

2020-01-06 09:54 UTC, xiaozhu36 commented on locals.tf
> +  resource_group_id = local.vswitch_resource_group_id
这个也是一样，vswitch和vpc的datasource都可以去掉

2020-01-06 09:54 UTC, xiaozhu36 commented on main.tf
> +module "account" {
module "account" -> module "accounts"

2020-01-06 09:54 UTC, xiaozhu36 commented on modules/account/variables.tf
> +//  default     = ""
不用的参数可以直接去掉了

2020-01-06 09:54 UTC, xiaozhu36 commented on modules/account/variables.tf
> +  description = "A list mapping used to add multiple accounts. Each item supports keys: account_name, account_password and account_privilege."
item的key可以直接是name，password，privilege了

2020-01-06 09:54 UTC, xiaozhu36 commented on modules/redis/README.md
> +  source  = "alibaba/redis-instance/alicloud//modules/redis"
这个应该是 terraform-alicloud-modules/redis/alicloud//modules/redis

2020-01-06 09:54 UTC, xiaozhu36 commented on modules/redis/variables.tf
> +  default     = ""
instance  name 可以不为空

2020-01-06 09:54 UTC, xiaozhu36 commented on variables.tf
> +  default     = ""
既然已经是redis了，instance_type 可以不用暴露，直接写死为 redis

2020-01-07 03:51 UTC, xiaozhu36 requested changes

2020-01-07 03:51 UTC, xiaozhu36 commented on README.md
> +    },
account type也是要放在accounts中的，可以给他一个default值

2020-01-07 03:51 UTC, xiaozhu36 commented on examples/redis/main.tf
> +variable "availability_zone" {
example中就不用写这个availability_zone了

2020-01-07 03:51 UTC, xiaozhu36 commented on main.tf
> +  backup_time   = var.backup_time
把涉及到的所有参数都写上

2020-01-07 03:51 UTC, xiaozhu36 commented on main.tf
> +  instance_charge_type = var.instance_charge_type
补全其他的参数

2020-01-07 03:51 UTC, xiaozhu36 commented on modules/account/outputs.tf
> +  value = alicloud_kvstore_account.this.*.account_name
输出更多的参数

2020-01-07 03:51 UTC, xiaozhu36 commented on modules/account/variables.tf
> +  description = "Privilege type of account.Normal: Common privilege. Super: High privilege.Default to Normal. It is is valid for MySQL 5.5/5.6 only."
这个描述不符吧

2020-01-08 10:54 UTC, xiaozhu36 requested changes

2020-01-08 10:54 UTC, xiaozhu36 commented on README-CN.md
> +* [云服务器account实例_(redis_account)](https://www.terraform.io/docs/providers/alicloud/r/kvstore_account.html)
Redis 数据库实例
Redis 数据库实例的备份策略
Redis 数据库的账号

2020-01-08 10:54 UTC, xiaozhu36 commented on examples/redis/main.tf
> +  }
tags的设置挪到security_ips的下面

2020-01-08 10:54 UTC, xiaozhu36 commented on modules/account/variables.tf
> +  description = "Whether to create a new account"
要写清楚，如果为true，什么参数不应该为空

2020-01-08 12:59 UTC, xiaozhu36 requested changes

2020-01-08 12:59 UTC, xiaozhu36 commented on modules/account/variables.tf
> +  description = "Whether to create a new account. If true, the `account_name` should not be empty."
哪有 account_name 这个参数啊

2020-01-08 12:59 UTC, xiaozhu36 commented on modules/redis/outputs.tf
> +output "this_redis_instanc_availability_zone" {
instance写全了

2020-01-08 12:59 UTC, xiaozhu36 commented on modules/redis/variables.tf
> +  description = "The Id of an existing redis instance. If set, the `create` will be ignored."
到底是create还是create_instance

2020-01-08 12:59 UTC, xiaozhu36 commented on modules/redis/variables.tf
> +  description = "Create instance"
描述不是简单的把参数名称中的下划线去掉就完了，要说清楚含义

2020-01-08 12:59 UTC, xiaozhu36 commented on modules/redis/variables.tf
> +  description = "A list mapping used to add multiple accounts. Each item supports keys: account_name, account_password,account_type(default to Normal and account_privilege(default to RoleReadOnly."
这是啥描述

2020-01-08 12:59 UTC, xiaozhu36 commented on README-CN.md
> +      account_type      = "Normal"
下面这个account中把type和privilege省略掉

2020-01-09 04:08 UTC, xiaozhu36 requested changes

2020-01-09 04:08 UTC, xiaozhu36 commented on variables.tf
> +  description = "redis instance type. Refer the Redis instance type reference, such as 'redis.master.small.default', 'redis.master.4xlarge.default', 'redis.sharding.mid.default' etc"
首字母大写

2020-01-09 04:08 UTC, xiaozhu36 commented on variables.tf
> +  description = "A list mapping used to add multiple accounts. Each item supports keys: account_name, account_password,account_type(default to Normal) and account_privilege(default to RoleReadOnly)."
都好后面的空格

2020-01-09 04:12 UTC, xiaozhu36 requested changes

2020-01-09 04:12 UTC, xiaozhu36 commented on modules/account/outputs.tf
> +  value = concat(alicloud_kvstore_account.this.*.account_name, [""])[0]
不是所有的都要concat，这个是一个list，保留list就行

2020-01-09 06:30 UTC, xiaozhu36 requested changes

2020-01-09 06:30 UTC, xiaozhu36 commented on outputs.tf
> +  description = "This redis instance availability zone."
The availability zone in which redis instance.

2020-01-09 06:30 UTC, xiaozhu36 commented on outputs.tf
> +  description = "This redis instance vswitch id."
The id of vswitch in which redis instance.

2020-01-09 06:30 UTC, xiaozhu36 commented on variables.tf
> +  default     = "MyRedis"
主module中的default要去掉

2020-01-09 06:30 UTC, xiaozhu36 commented on variables.tf
> +  description = "A mapping of tags to assign to the resource."
A mapping of tags to assign to the redis instance resource.

2020-01-09 06:40 UTC, xiaozhu36 approved these changes

2020-01-09 06:40 UTC, merged